#!/bin/sh
# vim: filetype=sh
#
# Description:	Universal interactive shell-startup.
#
# put your aliases here
#

# If not running interactively, don't do anything
[ "$-" = "${-%i*}" ] && return

# Load shortcuts
SHORTCUT=$XDG_CACHE_HOME/shortcutrc
[ -f "$SHORTCUT" ] && . "$SHORTCUT"
#---- less colors for man pages ------------------------------------------------
export LESS_TERMCAP_mb=$'\E[5;93m'   # Begin blinking -> Bright Yellow
export LESS_TERMCAP_md=$'\E[1;94m'   # Begin Bold -> Bright Blue
export LESS_TERMCAP_me=$'\E[0m'      # End mode
export LESS_TERMCAP_se=$'\E[0m'      # End standout-mode
export LESS_TERMCAP_so=$'\E[105;30m' # Begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'      # End underline
export LESS_TERMCAP_us=$'\E[4;92m'   # Begin underline -> Bright Green
export GROFF_NO_SGR=1
#---- GPG ----------------------------------------------------------------------
export GPG_TTY=$(tty)

#-------- Preferred Apps ---------------
alias \
	e='$EDITOR'

#---- Modules ------------------------------------------------------------------
ssource $XDG_CONFIG_HOME/shell/mods/core.sh
ssource $XDG_CONFIG_HOME/shell/mods/git.sh
ssource $XDG_CONFIG_HOME/shell/mods/arch.sh
