local is_tty = require('sobh.utils').is_tty

if is_tty() then
	return {
		misc = { dots = "..." },
		fold = {
			open = '▾',
			close = '▸',
			sep = ' ',
		},
		diagnostics = {
			Error = "E",
			Warn  = "W",
			Hint  = "H",
			Info  = "I",
		},
		git = {
			added    = "+",
			modified = "~",
			removed  = "-",
			gutter = {
				added     = "+",
				modified  = "|",
				removed   = "-",
				untracked = "?",
			},
		},
		kinds = {
			Array         = "[]",
			Boolean       = "b",
			Class         = "C",
			Color         = "#",
			Constant      = "c",
			Constructor   = "C",
			Enum          = "E",
			EnumMember    = "e",
			Event         = "!",
			Field         = ".",
			File          = "f",
			Folder        = "d",
			Function      = "fn",
			Interface     = "I",
			Key           = "k",
			Keyword       = "K",
			Method        = "m",
			Module        = "M",
			Namespace     = "N",
			Null          = "0",
			Number        = "#",
			Object        = "O",
			Operator      = "op",
			Package       = "P",
			Property      = ".",
			Reference     = "&",
			Snippet       = "S",
			String        = "s",
			Struct        = "S",
			Text          = "T",
			TypeParameter = "T",
			Unit          = "U",
			Value         = "v",
			Variable      = "V",
		},
	}
end

return {
	misc = {
		dots = "󰇘",
	},
	fold = {
		-- open = '',
		-- close = '',
		open = '▾',
		close = '▸',
		sep = ' ',
	},
	dap = {
		Stopped             = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
		Breakpoint          = " ",
		BreakpointCondition = " ",
		BreakpointRejected  = { " ", "DiagnosticError" },
		LogPoint            = ".>",
	},
	diagnostics = {
		Error = " ",
		Warn  = " ",
		Hint  = " ",
		Info  = " ",
	},
	git = {
		added    = " ",
		modified = " ",
		removed  = " ",
		gutter = {
			added     = " ",
			modified  = "│",
			removed   = " ",
			untracked = "┆ ",
		},
	},
	kinds = {
		Array         = " ",
		Boolean       = "󰨙 ",
		Class         = " ",
		Codeium       = "󰘦 ",
		Color         = " ",
		Control       = " ",
		Collapsed     = " ",
		Constant      = "󰏿 ",
		Constructor   = " ",
		Copilot       = " ",
		Enum          = " ",
		EnumMember    = " ",
		Event         = " ",
		Field         = " ",
		File          = " ",
		Folder        = " ",
		Function      = "󰊕 ",
		Interface     = " ",
		Key           = " ",
		Keyword       = " ",
		Method        = "󰊕 ",
		Module        = " ",
		Namespace     = "󰦮 ",
		Null          = " ",
		Number        = "󰎠 ",
		Object        = " ",
		Operator      = " ",
		Package       = " ",
		Property      = " ",
		Reference     = " ",
		Snippet       = " ",
		String        = " ",
		Struct        = "󰆼 ",
		TabNine       = "󰏚 ",
		Text          = " ",
		TypeParameter = " ",
		Unit          = " ",
		Value         = " ",
		Variable      = "󰀫 ",
	},
}
