[colors.primary]
background = "#$background"
foreground = "#$foreground"

[colors.normal]
black   = "#$normal_black"
red     = "#$normal_red"
green   = "#$normal_green"
yellow  = "#$normal_yellow"
blue    = "#$normal_blue"
cyan    = "#$normal_cyan"
magenta = "#$normal_magenta"
white   = "#$normal_white"

[colors.bright]
black   = "#$bright_black"
red     = "#$bright_red"
green   = "#$bright_green"
yellow  = "#$bright_yellow"
blue    = "#$bright_blue"
cyan    = "#$bright_cyan"
magenta = "#$bright_magenta"
white   = "#$bright_white"
