# vim: filetype=sh
#
# Description:	Linux specific 'xinitrc' file.
#

#---- Applications -------------------------------------------------------------
#-------- i3 -----------------------------------------------
export SWAY_I3_STATUS_CMD=i3blocks
