[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.normal]
black   = "#000000"
red     = "#e03131"
green   = "#2f9e44"
yellow  = "#f08c00"
blue    = "#3b5bdb"
cyan    = "#0c8599"
magenta = "#9c36b5"
white   = "#ced4da"

[colors.bright]
black   = "#868e96"
red     = "#c2255c"
green   = "#66a80f"
yellow  = "#e8590c"
blue    = "#1971c2"
cyan    = "#099268"
magenta = "#6741d9"
white   = "#ffffff"
